/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 06-May-2023 12:40:28 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */

DROP TABLE IF EXISTS `Customer`
;

DROP TABLE IF EXISTS `Jobs`
;

DROP TABLE IF EXISTS `Order`
;

DROP TABLE IF EXISTS `prices`
;

DROP TABLE IF EXISTS `product`
;

DROP TABLE IF EXISTS `product_big_catgory`
;

DROP TABLE IF EXISTS `product_category`
;

DROP TABLE IF EXISTS `product_group`
;

DROP TABLE IF EXISTS `Users`
;

/* Create Tables */

CREATE TABLE `Customer`
(
	`id` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	`address1` VARCHAR(50) NULL,
	`address2` VARCHAR(50) NULL,
	`address3` VARCHAR(50) NULL,
	`address4` VARCHAR(50) NULL,
	`address5` VARCHAR(50) NULL,
	`postcode` VARCHAR(50) NULL,
	`countrycode` VARCHAR(50) NULL,
	`category` VARCHAR(50) NULL,
	`workgroup` VARCHAR(50) NULL,
	`payment_terms_code` VARCHAR(50) NULL,
	`payment_terms_description` VARCHAR(50) NULL,
	CONSTRAINT `PK_Customer` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Jobs`
(
	`id` VARCHAR(50) NOT NULL,
	`status` VARCHAR(50) NULL,
	`customer` VARCHAR(50) NULL,
	`cotact` VARCHAR(50) NULL,
	`quantity_allocated` VARCHAR(50) NULL,
	`quantity_printed` VARCHAR(50) NULL,
	`quantity_despatched` VARCHAR(50) NULL,
	`total_transfer` VARCHAR(50) NULL,
	`total_selling` VARCHAR(50) NULL,
	`total` VARCHAR(50) NULL,
	`product_code` VARCHAR(50) NULL,
	`client_reference` VARCHAR(50) NULL,
	`title` VARCHAR(50) NULL,
	`category` VARCHAR(50) NULL,
	`quantity` VARCHAR(50) NULL,
	`auto081` VARCHAR(50) NULL,
	`service` VARCHAR(50) NULL,
	`status_text` VARCHAR(50) NULL,
	`complete` VARCHAR(50) NULL,
	`multifile` VARCHAR(50) NULL,
	`expected_despatch_date` VARCHAR(50) NULL,
	`front_filename` VARCHAR(50) NULL,
	`reverse_filename` VARCHAR(50) NULL,
	`fee_charged_on_job` VARCHAR(50) NULL,
	`pages` VARCHAR(50) NULL,
	`job_comments` VARCHAR(50) NULL,
	CONSTRAINT `PK_Jobs` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Order`
(
	`id` VARCHAR(50) NOT NULL,
	`contact` VARCHAR(50) NULL,
	`customer` VARCHAR(50) NULL,
	`title` VARCHAR(50) NULL,
	`reference` VARCHAR(50) NULL,
	`date` VARCHAR(50) NULL,
	CONSTRAINT `PK_Order` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `prices`
(
	`id` VARCHAR(50) NOT NULL,
	`selling` VARCHAR(50) NULL,
	`transfer` VARCHAR(50) NULL,
	`production` VARCHAR(50) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `product`
(
	`id` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	`filetype` VARCHAR(50) NULL,
	`width` VARCHAR(50) NULL,
	`height` VARCHAR(50) NULL,
	`bleed` VARCHAR(50) NULL,
	`rununits` VARCHAR(50) NULL,
	`reverse` VARCHAR(50) NULL,
	`allowmulti` VARCHAR(50) NULL,
	`partnercode` VARCHAR(50) NULL,
	`language` VARCHAR(50) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `product_big_catgory`
(
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	CONSTRAINT `PK_product_big_catgory` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `product_category`
(
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	`prodzone` VARCHAR(50) NULL,
	CONSTRAINT `PK_product_category` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `product_group`
(
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NULL,
	`url_slug` VARCHAR(50) NULL,
	`prodcat` VARCHAR(50) NULL,
	CONSTRAINT `PK_product_group` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `Users`
(
	`idUser` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	`password` VARCHAR(50) NULL,
	`images` TEXT NULL,
	`userType` VARCHAR(50) NULL,
	CONSTRAINT `PK_Users` PRIMARY KEY (`idUser` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Jobs`
 ADD CONSTRAINT `FK_Jobs_Order`
	FOREIGN KEY (`id`) REFERENCES `Order` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Jobs`
 ADD CONSTRAINT `FK_Jobs_product`
	FOREIGN KEY (`product_code`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Order`
 ADD CONSTRAINT `FK_Order_Customer`
	FOREIGN KEY (`customer`) REFERENCES `Customer` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `prices`
 ADD CONSTRAINT `FK_prices_product`
	FOREIGN KEY (`id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product_category`
 ADD CONSTRAINT `FK_product_category_product_big_catgory`
	FOREIGN KEY (`prodzone`) REFERENCES `product_big_catgory` (`code`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `product_group`
 ADD CONSTRAINT `FK_product_group_product_category`
	FOREIGN KEY (`prodcat`) REFERENCES `product_category` (`code`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;
